apiVersion: apps/v1
kind: Deployment
metadata:
  name: softoolshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softoolshop
  template:
    metadata:
      labels:
        app: softoolshop
    spec:
      containers:
      - name: softoolshop
        image: inddocker786/softoolshop-dev:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: softoolshop-service
spec:
  type: ClusterIP
  selector:
    app: softoolshop
  ports:
  - port: 8080
    targetPort: 8080
